on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ESLint-Evaluator:
    runs-on: self-hosted
    name: ESLint
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3.1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

  evaluator:
    runs-on: self-hosted
    name: Evaluator
    needs: [ESLint-Evaluator]
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Jest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/jest-evaluator-action
          ref: v9.1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/jest-evaluator

      - name: Fetch Evaluation Feedback
        uses: actions/checkout@v2
        with:
          repository: betrybe/evaluation-feedback-action
          ref: v1.0.0
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/evaluation-feedback

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.6
        with:
          node-version: '16'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run Jest evaluator
        id: evaluator
        uses: ./.github/actions/jest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
          npm-start: true

      - name: Run Evaluation Feedback
        uses: ./.github/actions/evaluation-feedback
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
